---
# tasks file for juju4.tailon

- name: Set fact is_container
  ansible.builtin.set_fact:
    is_container: true
  when: >
    (ansible_facts['virtualization_type'] is defined and
      (ansible_facts['virtualization_type'] == "docker"
       or ansible_facts['virtualization_type'] == "containerd"
       or ansible_facts['virtualization_type'] == "container"
      )
    )

- name: Import tailon
  ansible.builtin.import_tasks: tailon.yml
- name: Import logs-acl
  ansible.builtin.import_tasks: logs-acl.yml
- name: Import systemd
  ansible.builtin.import_tasks: systemd.yml
- name: Import rsyslog-tailon
  ansible.builtin.import_tasks: rsyslog-tailon.yml
